FROM openjdk:8

WORKDIR /usrapp/bin

ENV PORT 6000

COPY /target/classes /usrapp/bin/classes
COPY /target/dependency /usrapp/bin/dependency

CMD ["java","-cp","./claSsses:./dependency/*","co.edu.escuelaing.sparkdockerdemolive.Parcial2AREP"]


